<Project>
  <Name>Gang of Four</Name>
  <ProjectItem type="NClass.DiagramEditor.ClassDiagram.Diagram" assembly="NClass.DiagramEditor, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null">
    <Name>Factory Method</Name>
    <Language>C#</Language>
    <Entities>
      <Entity type="Class">
        <Name>ProductBase</Name>
        <Access>Public</Access>
        <Location left="66" top="59" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>Abstract</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>FactoryBase</Name>
        <Access>Public</Access>
        <Location left="302" top="59" />
        <Size width="179" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public abstract ProductBase FactoryMethod()</Member>
        <Modifier>Abstract</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteFactory</Name>
        <Access>Public</Access>
        <Location left="302" top="230" />
        <Size width="179" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public override ProductBase FactoryMethod()</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteProduct</Name>
        <Access>Public</Access>
        <Location left="64" top="230" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>None</Modifier>
      </Entity>
    </Entities>
    <Relationships>
      <Relationship type="Generalization" first="2" second="1">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
      </Relationship>
      <Relationship type="Dependency" first="2" second="3">
        <Label>
        </Label>
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
      </Relationship>
      <Relationship type="Generalization" first="3" second="0">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
      </Relationship>
    </Relationships>
  </ProjectItem>
  <ProjectItem type="NClass.DiagramEditor.ClassDiagram.Diagram" assembly="NClass.DiagramEditor, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null">
    <Name>Singleton</Name>
    <Language>C#</Language>
    <Entities>
      <Entity type="Class">
        <Name>Singleton</Name>
        <Access>Public</Access>
        <Location left="31" top="31" />
        <Size width="163" height="128" />
        <Collapsed>False</Collapsed>
        <Member type="Field">Singleton instance</Member>
        <Member type="Constructor">private Singleton()</Member>
        <Member type="Method">public Singleton GetSingleton()</Member>
        <Modifier>None</Modifier>
      </Entity>
    </Entities>
    <Relationships />
  </ProjectItem>
  <ProjectItem type="NClass.DiagramEditor.ClassDiagram.Diagram" assembly="NClass.DiagramEditor, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null">
    <Name>Builder</Name>
    <Language>C#</Language>
    <Entities>
      <Entity type="Class">
        <Name>Director</Name>
        <Access>Public</Access>
        <Location left="55" top="28" />
        <Size width="188" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public void Construct(Builder builder)</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>Builder</Name>
        <Access>Public</Access>
        <Location left="356" top="28" />
        <Size width="163" height="128" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public abstract void BuildPart1()</Member>
        <Member type="Method">public abstract void BuildPartX()</Member>
        <Member type="Method">public abstract Product GetProduct()</Member>
        <Modifier>Abstract</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteBuilder</Name>
        <Access>Public</Access>
        <Location left="356" top="220" />
        <Size width="163" height="128" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public override void BuildPart1()</Member>
        <Member type="Method">public override void BuildPartX()</Member>
        <Member type="Method">public override Product GetProduct()</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>Product</Name>
        <Access>Public</Access>
        <Location left="69" top="220" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>None</Modifier>
      </Entity>
    </Entities>
    <Relationships>
      <Relationship type="Generalization" first="2" second="1">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
      </Relationship>
      <Relationship type="Association" first="0" second="1">
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <Direction>Bidirectional</Direction>
        <AssociationType>Aggregation</AssociationType>
      </Relationship>
      <Relationship type="Dependency" first="2" second="3">
        <Label>
        </Label>
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>320</X>
          <Y>259</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>274</X>
          <Y>259</Y>
        </BendPoint>
      </Relationship>
    </Relationships>
  </ProjectItem>
  <ProjectItem type="NClass.DiagramEditor.ClassDiagram.Diagram" assembly="NClass.DiagramEditor, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null">
    <Name>Abstract Factory</Name>
    <Language>C#</Language>
    <Entities>
      <Entity type="Class">
        <Name>Client</Name>
        <Access>Public</Access>
        <Location left="428" top="45" />
        <Size width="211" height="128" />
        <Collapsed>False</Collapsed>
        <Member type="Field">AbstractProductA productA</Member>
        <Member type="Field">AbstractProductB productB</Member>
        <Member type="Method">public void Client(AbstractFactory factory)</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>AbstractFactory</Name>
        <Access>Public</Access>
        <Location left="441" top="228" />
        <Size width="206" height="111" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public abstract AbstractProductA CreateProductA()</Member>
        <Member type="Method">public abstract AbstractProductB CreateProductB()</Member>
        <Modifier>Abstract</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>AbstractProductB</Name>
        <Access>Public</Access>
        <Location left="739" top="228" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>Abstract</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>AbstractProductA</Name>
        <Access>Public</Access>
        <Location left="177" top="228" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>Abstract</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteFactoryA</Name>
        <Access>Public</Access>
        <Location left="330" top="424" />
        <Size width="206" height="111" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public override AbstractProductA CreateProductA()</Member>
        <Member type="Method">public override AbstractProductB CreateProductB()</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteFactoryB</Name>
        <Access>Public</Access>
        <Location left="484" top="612" />
        <Size width="206" height="111" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public override AbstractProductA CreateProductA()</Member>
        <Member type="Method">public override AbstractProductB CreateProductB()</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteProductB1</Name>
        <Access>Public</Access>
        <Location left="844" top="440" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteProductB2</Name>
        <Access>Public</Access>
        <Location left="775" top="612" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteProductA1</Name>
        <Access>Public</Access>
        <Location left="73" top="465" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcreteProductA2</Name>
        <Access>Public</Access>
        <Location left="162" top="597" />
        <Size width="163" height="77" />
        <Collapsed>False</Collapsed>
        <Modifier>None</Modifier>
      </Entity>
    </Entities>
    <Relationships>
      <Relationship type="Association" first="0" second="2">
        <Label>
        </Label>
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>582</X>
          <Y>201</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>822</X>
          <Y>202</Y>
        </BendPoint>
        <Direction>Unidirectional</Direction>
        <AssociationType>Association</AssociationType>
      </Relationship>
      <Relationship type="Association" first="0" second="1">
        <Label>
        </Label>
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <Direction>Unidirectional</Direction>
        <AssociationType>Association</AssociationType>
      </Relationship>
      <Relationship type="Association" first="0" second="3">
        <Label>
        </Label>
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>477</X>
          <Y>198</Y>
        </BendPoint>
        <Direction>Unidirectional</Direction>
        <AssociationType>Association</AssociationType>
      </Relationship>
      <Relationship type="Generalization" first="4" second="1">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="False">
          <X>498</X>
          <Y>364</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Generalization" first="5" second="1">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="False">
          <X>592</X>
          <Y>366</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Generalization" first="7" second="2">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>804</X>
          <Y>516</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>804</X>
          <Y>391</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Generalization" first="6" second="2">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>870</X>
          <Y>407</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>870</X>
          <Y>363</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Dependency" first="4" second="6">
        <Label>
        </Label>
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>568</X>
          <Y>478</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>783</X>
          <Y>476</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Generalization" first="8" second="3">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>217</X>
          <Y>431</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>217</X>
          <Y>337</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Generalization" first="9" second="3">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
        <BendPoint relativeToStartShape="False">
          <X>266</X>
          <Y>333</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Dependency" first="4" second="8">
        <Label>
        </Label>
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <BendPoint relativeToStartShape="True">
          <X>299</X>
          <Y>506</Y>
        </BendPoint>
        <BendPoint relativeToStartShape="False">
          <X>270</X>
          <Y>506</Y>
        </BendPoint>
      </Relationship>
      <Relationship type="Dependency" first="5" second="9">
        <Label>
        </Label>
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
      </Relationship>
      <Relationship type="Dependency" first="5" second="7">
        <Label>
        </Label>
        <StartOrientation>Horizontal</StartOrientation>
        <EndOrientation>Horizontal</EndOrientation>
        <BendPoint relativeToStartShape="False">
          <X>735</X>
          <Y>651</Y>
        </BendPoint>
      </Relationship>
    </Relationships>
  </ProjectItem>
  <ProjectItem type="NClass.DiagramEditor.ClassDiagram.Diagram" assembly="NClass.DiagramEditor, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null">
    <Name>Prototype</Name>
    <Language>C#</Language>
    <Entities>
      <Entity type="Class">
        <Name>Prototype</Name>
        <Access>Public</Access>
        <Location left="254" top="31" />
        <Size width="163" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public Prototype Clone()</Member>
        <Modifier>Abstract</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcretePrototypeB</Name>
        <Access>Public</Access>
        <Location left="381" top="203" />
        <Size width="163" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public Prototype Clone()</Member>
        <Modifier>None</Modifier>
      </Entity>
      <Entity type="Class">
        <Name>ConcretePrototypeA</Name>
        <Access>Public</Access>
        <Location left="128" top="203" />
        <Size width="163" height="94" />
        <Collapsed>False</Collapsed>
        <Member type="Method">public Prototype Clone()</Member>
        <Modifier>None</Modifier>
      </Entity>
    </Entities>
    <Relationships>
      <Relationship type="Generalization" first="2" second="0">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
      </Relationship>
      <Relationship type="Generalization" first="1" second="0">
        <StartOrientation>Vertical</StartOrientation>
        <EndOrientation>Vertical</EndOrientation>
      </Relationship>
    </Relationships>
  </ProjectItem>
</Project>